package app.gamenative.preferences

interface ContainerPreferences {
    var screenSize: String
    var envVars: String
    var graphicsDriver: String
    var graphicsDriverVersion: String
    var graphicsDriverConfig: String
    var rendererPresentMode: String
    var displayRendererMode: String
    var sfCompatMode: Boolean
    var useLegacyRenderer: Boolean
    var sharpnessEffect: String
    var sharpnessLevel: Int
    var sharpnessDenoise: Int
    var containerVariant: String
    var wineVersion: String
    var emulator: String
    var fexcoreVersion: String
    var fexcoreTSOMode: String
    var fexcoreX87Mode: String
    var fexcoreMultiBlock: String
    var fexcorePreset: String
    var box86Preset: String
    var box64Preset: String
    var box86Version: String
    var box64Version: String
    var dxWrapper: String
    var dxWrapperConfig: String
    var audioDriver: String
    var pulseaudioLowLatency: Boolean
    var winComponents: String
    var drives: String
    var execArgs: String
    var suspendPolicy: String
    var cpuList: String
    var cpuListWoW64: String
    var wow64Mode: Boolean
    var startupSelection: Int
    var containerLanguage: String
    var renderer: String
    var csmt: Boolean
    var videoPciDeviceID: Int
    var offScreenRenderingMode: String
    var strictShaderMath: Boolean
    var useDRI3: Boolean
    var videoMemorySize: String
    var mouseWarpOverride: String
    var portraitMode: Boolean
    var launchRealSteam: Boolean
    var launchBionicSteam: Boolean
    var forceDlc: Boolean
    var localSavesOnly: Boolean
    var useLegacyDRM: Boolean
    var unpackFiles: Boolean
    var autoApplyKnownConfig: Boolean
    var enableWineDebug: Boolean
    var wineDebugChannels: String
}
